services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile # Add this line to tell Docker to use your lowercase file
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_URI=mongodb://mongodb:27017/total_records


volumes:
  mongodb_data:
